# Generated by Django 3.0 on 2022-12-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cooking_time', models.IntegerField()),
                ('number_of_servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('tags', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=150)),
                ('author_link', models.CharField(max_length=150)),
                ('quote', models.TextField()),
                ('preview_photo', models.ImageField(upload_to='preview_photo/')),
                ('views', models.IntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=150)),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Type')),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Complexity')),
            ],
        ),
    ]
