# Generated by Django 3.0 on 2022-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221209_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexity',
            options={'verbose_name': 'Уровень сложности готовки', 'verbose_name_plural': 'Уровни сложности готовки'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюд'},
        ),
    ]
