# Generated by Django 3.0 on 2022-12-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221209_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.Type_of_kitchen'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='complexity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.Complexity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
